- name: My first play
  hosts: "{{ target_hosts }}"
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world
      
   - name: Force this play to fail
      ansible.builtin.fail:
        msg: "This playbook is intentionally set to fail."
